FROM ubuntu:20.04
RUN apt-get update
RUN apt upgrade -y
# ip ping nslookup traceroute
RUN apt install -y iproute2 iputils-ping bind9-dnsutils traceroute
RUN apt install -y cron
RUN apt install -y curl git less unzip vim wget
RUN apt install -y sudo
RUN apt install -y gpg
RUN apt install -y lsb-release
RUN apt install -y bash-completion
